// ////////////////////////////////////////////////////////////
const countries = [
  // Asia
  { country: "Afghanistan", short: "AFG" },
  { country: "Armenia", short: "ARM" },
  { country: "Azerbaijan", short: "AZE" },
  { country: "Bahrain", short: "BHR" },
  { country: "Bangladesh", short: "BGD" },
  { country: "Bhutan", short: "BTN" },
  { country: "Brunei", short: "BRN" },
  { country: "Cambodia", short: "KHM" },
  { country: "China", short: "CHN" },
  { country: "Cyprus", short: "CYP" },
  { country: "Georgia", short: "GEO" },
  { country: "India", short: "IND" },
  { country: "Indonesia", short: "IDN" },
  { country: "Iran", short: "IRN" },
  { country: "Iraq", short: "IRQ" },
  { country: "Israel", short: "ISR" },
  { country: "Japan", short: "JPN" },
  { country: "Jordan", short: "JOR" },
  { country: "Kazakhstan", short: "KAZ" },
  { country: "Kuwait", short: "KWT" },
  { country: "Kyrgyzstan", short: "KGZ" },
  { country: "Laos", short: "LAO" },
  { country: "Lebanon", short: "LBN" },
  { country: "Malaysia", short: "MYS" },
  { country: "Maldives", short: "MDV" },
  { country: "Mongolia", short: "MNG" },
  { country: "Myanmar", short: "MMR" },
  { country: "Nepal", short: "NPL" },
  { country: "North Korea", short: "PRK" },
  { country: "Oman", short: "OMN" },
  { country: "Pakistan", short: "PAK" },
  { country: "Palestine", short: "PSE" },
  { country: "Philippines", short: "PHL" },
  { country: "Qatar", short: "QAT" },
  { country: "Russia", short: "RUS" },
  { country: "Saudi Arabia", short: "SAU" },
  { country: "Singapore", short: "SGP" },
  { country: "South Korea", short: "KOR" },
  { country: "Sri Lanka", short: "LKA" },
  { country: "Syria", short: "SYR" },
  { country: "Tajikistan", short: "TJK" },
  { country: "Thailand", short: "THA" },
  { country: "Timor-Leste", short: "TLS" },
  { country: "Turkey", short: "TUR" },
  { country: "Turkmenistan", short: "TKM" },
  { country: "United Arab Emirates", short: "ARE" },
  { country: "Uzbekistan", short: "UZB" },
  { country: "Vietnam", short: "VNM" },
  { country: "Yemen", short: "YEM" },

  // Europe
  { country: "Albania", short: "ALB" },
  { country: "Andorra", short: "AND" },
  { country: "Austria", short: "AUT" },
  { country: "Belarus", short: "BLR" },
  { country: "Belgium", short: "BEL" },
  { country: "Bosnia and Herzegovina", short: "BIH" },
  { country: "Bulgaria", short: "BGR" },
  { country: "Croatia", short: "HRV" },
  { country: "Czech Republic", short: "CZE" },
  { country: "Denmark", short: "DNK" },
  { country: "Estonia", short: "EST" },
  { country: "Finland", short: "FIN" },
  { country: "France", short: "FRA" },
  { country: "Germany", short: "DEU" },
  { country: "Greece", short: "GRC" },
  { country: "Hungary", short: "HUN" },
  { country: "Iceland", short: "ISL" },
  { country: "Ireland", short: "IRL" },
  { country: "Italy", short: "ITA" },
  { country: "Kosovo", short: "XKX" },
  { country: "Latvia", short: "LVA" },
  { country: "Liechtenstein", short: "LIE" },
  { country: "Lithuania", short: "LTU" },
  { country: "Luxembourg", short: "LUX" },
  { country: "Malta", short: "MLT" },
  { country: "Moldova", short: "MDA" },
  { country: "Monaco", short: "MCO" },
  { country: "Montenegro", short: "MNE" },
  { country: "Netherlands", short: "NLD" },
  { country: "North Macedonia", short: "MKD" },
  { country: "Norway", short: "NOR" },
  { country: "Poland", short: "POL" },
  { country: "Portugal", short: "PRT" },
  { country: "Romania", short: "ROU" },
  { country: "San Marino", short: "SMR" },
  { country: "Serbia", short: "SRB" },
  { country: "Slovakia", short: "SVK" },
  { country: "Slovenia", short: "SVN" },
  { country: "Spain", short: "ESP" },
  { country: "Sweden", short: "SWE" },
  { country: "Switzerland", short: "CHE" },
  { country: "Ukraine", short: "UKR" },
  { country: "United Kingdom", short: "GBR" },
  { country: "Vatican City", short: "VAT" },
  // Africa
  { country: "Algeria", short: "DZA" },
  { country: "Angola", short: "AGO" },
  { country: "Benin", short: "BEN" },
  { country: "Botswana", short: "BWA" },
  { country: "Burkina Faso", short: "BFA" },
  { country: "Burundi", short: "BDI" },
  { country: "Cabo Verde", short: "CPV" },
  { country: "Cameroon", short: "CMR" },
  { country: "Central African Republic", short: "CAF" },
  { country: "Chad", short: "TCD" },
  { country: "Comoros", short: "COM" },
  { country: "Congo (Congo-Brazzaville)", short: "COG" },
  { country: "Congo (DRC)", short: "COD" },
  { country: "Djibouti", short: "DJI" },
  { country: "Egypt", short: "EGY" },
  { country: "Equatorial Guinea", short: "GNQ" },
  { country: "Eritrea", short: "ERI" },
  { country: "Eswatini (Swaziland)", short: "SWZ" },
  { country: "Ethiopia", short: "ETH" },
  { country: "Gabon", short: "GAB" },
  { country: "Gambia", short: "GMB" },
  { country: "Ghana", short: "GHA" },
  { country: "Guinea", short: "GIN" },
  { country: "Guinea-Bissau", short: "GNB" },
  { country: "Ivory Coast", short: "CIV" },
  { country: "Kenya", short: "KEN" },
  { country: "Lesotho", short: "LSO" },
  { country: "Liberia", short: "LBR" },
  { country: "Libya", short: "LBY" },
  { country: "Madagascar", short: "MDG" },
  { country: "Malawi", short: "MWI" },
  { country: "Mali", short: "MLI" },
  { country: "Mauritania", short: "MRT" },
  { country: "Mauritius", short: "MUS" },
  { country: "Morocco", short: "MAR" },
  { country: "Mozambique", short: "MOZ" },
  { country: "Namibia", short: "NAM" },
  { country: "Niger", short: "NER" },
  { country: "Nigeria", short: "NGA" },
  { country: "Rwanda", short: "RWA" },
  { country: "Sao Tome and Principe", short: "STP" },
  { country: "Senegal", short: "SEN" },
  { country: "Seychelles", short: "SYC" },
  { country: "Sierra Leone", short: "SLE" },
  { country: "Somalia", short: "SOM" },
  { country: "South Africa", short: "ZAF" },
  { country: "South Sudan", short: "SSD" },
  { country: "Sudan", short: "SDN" },
  { country: "Tanzania", short: "TZA" },
  { country: "Togo", short: "TGO" },
  { country: "Tunisia", short: "TUN" },
  { country: "Uganda", short: "UGA" },
  { country: "Zambia", short: "ZMB" },
  { country: "Zimbabwe", short: "ZWE" },

  // North America
  { country: "Antigua and Barbuda", short: "ATG" },
  { country: "Bahamas", short: "BHS" },
  { country: "Barbados", short: "BRB" },
  { country: "Belize", short: "BLZ" },
  { country: "Canada", short: "CAN" },
  { country: "Costa Rica", short: "CRI" },
  { country: "Cuba", short: "CUB" },
  { country: "Dominica", short: "DMA" },
  { country: "Dominican Republic", short: "DOM" },
  { country: "El Salvador", short: "SLV" },
  { country: "Grenada", short: "GRD" },
  { country: "Guatemala", short: "GTM" },
  { country: "Haiti", short: "HTI" },
  { country: "Honduras", short: "HND" },
  { country: "Jamaica", short: "JAM" },
  { country: "Mexico", short: "MEX" },
  { country: "Nicaragua", short: "NIC" },
  { country: "Panama", short: "PAN" },
  { country: "Saint Kitts and Nevis", short: "KNA" },
  { country: "Saint Lucia", short: "LCA" },
  { country: "Saint Vincent and the Grenadines", short: "VCT" },
  { country: "Trinidad and Tobago", short: "TTO" },
  { country: "United States", short: "USA" },

  // South America
  { country: "Argentina", short: "ARG" },
  { country: "Bolivia", short: "BOL" },
  { country: "Brazil", short: "BRA" },
  { country: "Chile", short: "CHL" },
  { country: "Colombia", short: "COL" },
  { country: "Ecuador", short: "ECU" },
  { country: "Guyana", short: "GUY" },
  { country: "Paraguay", short: "PRY" },
  { country: "Peru", short: "PER" },
  { country: "Suriname", short: "SUR" },
  { country: "Uruguay", short: "URY" },
  { country: "Venezuela", short: "VEN" },

  // Oceania
  { country: "Australia", short: "AUS" },
  { country: "Fiji", short: "FJI" },
  { country: "Kiribati", short: "KIR" },
  { country: "Marshall Islands", short: "MHL" },
  { country: "Micronesia", short: "FSM" },
  { country: "Nauru", short: "NRU" },
  { country: "New Zealand", short: "NZL" },
  { country: "Palau", short: "PLW" },
  { country: "Papua New Guinea", short: "PNG" },
  { country: "Samoa", short: "WSM" },
  { country: "Solomon Islands", short: "SLB" },
  { country: "Tonga", short: "TON" },
  { country: "Tuvalu", short: "TUV" },
  { country: "Vanuatu", short: "VUT" },
];
export default countries;
